### ISSUE TITLE
Redis session data sometimes not present

### ISSUE THREAD

**Issue by tyressk** [PerfectlySoft/Perfect-Session-Redis#3]
**Session Configuration settings**:
```
#if os(Linux)
RedisSessionConnector.host = "redis"
#else
RedisSessionConnector.host = "127.0.0.1"
#endif
RedisSessionConnector.password = ""
RedisSessionConnector.port = redisDefaultPort
SessionConfig.name = "Session"
SessionConfig.idle = 3600
SessionConfig.cookieDomain = "hostnamehere"
SessionConfig.IPAddressLock = false
SessionConfig.userAgentLock = false
SessionConfig.CSRF.checkState = true
SessionConfig.CORS.enabled = false
SessionConfig.cookieSameSite = .lax
```
**Fields settings**:

```
response.request.session?.data["email"] = email
//etc
```

**Issue**: `request.session?.data[field]` is sometimes empty during a request
**Description**: Calling the endpoint sometimes returns a null string. Using MONITOR on redis-cli, this happens when the Perfect-Session-Redis calls the Redis Server "SET" command twice in succession using an unrelated key.

e.g.
```
1524209227.582179 [0 127.0.0.1:53006] "GET" "07E53CE2-6C89-4783-85D8-A682382FCB51"
1524209227.653548 [0 127.0.0.1:53008] "SET" "07E53CE2-6C89-4783-85D8-A682382FCB51" "{\"updated\":1524209166,\"idle\":3600,\”sample\”:\”data\”}" "PX" "3600000"
#Received session data
1524209227.783976 [0 127.0.0.1:53009] "GET" "07E53CE2-6C89-4783-85D8-A682382FCB51"
1524209227.854708 [0 127.0.0.1:53011] "SET" "07E53CE2-6C89-4783-85D8-A682382FCB51" "{\"updated\":1524209166,\"idle\":3600,\”sample\”:\”data\”}" "PX" "3600000"
#Received session data
1524209228.241178 [0 127.0.0.1:53015] "GET" "07E53CE2-6C89-4783-85D8-A682382FCB51"
1524209228.242038 [0 127.0.0.1:53016] "SET" "AE5ADF76-1D3E-4F6A-A7B9-1D448B56D621" "{\"updated\":1524209166,\"idle\":3600,\”sample\”:\”data\”}" "PX" "3600000"
1524209228.242829 [0 127.0.0.1:53017] "SET" "AE5ADF76-1D3E-4F6A-A7B9-1D448B56D621" "{\"updated\":1524209166,\"idle\":3600,\”sample\”:\”data\”}" "PX" "3600000"
#Did not receive session data
```

**Comment by kjessup** [comment]
Hello. I just pushed a new revision which I *think* will take care of this problem.

If you `swift package update` you will get a version tagged 3.0.2.

Please let me know if this resolves the issue.
Thank you!

**Comment by tyressk** [comment]
Thanks for the fast response @kjessup ! The GET SET SET pattern isn't happening anymore, but I still get the bug. The pattern looks like this now on MONITOR:

1524528933.228273 [0 127.0.0.1:50680] "GET" "B5EE1230-F973-418D-9881-936087C793A3"
1524528933.232004 [0 127.0.0.1:50682] "SET" "B5EE1230-F973-418D-9881-936087C793A3" “{\”correct\”:\”response\”}” "PX" "3600000"
1524528933.680522 [0 127.0.0.1:50683] "GET" "B5EE1230-F973-418D-9881-936087C793A3"
1524528933.683644 [0 127.0.0.1:50685] "SET" "B5EE1230-F973-418D-9881-936087C793A3" “{\”correct\”:\”response\”}” "PX" "3600000"
1524528934.199531 [0 127.0.0.1:50686] "GET" "B5EE1230-F973-418D-9881-936087C793A3"
1524528934.203061 [0 127.0.0.1:50688] "SET" "B5EE1230-F973-418D-9881-936087C793A3" “{\”correct\”:\”response\”}” "PX" "3600000"
1524528934.721564 [0 127.0.0.1:50689] "GET" "B5EE1230-F973-418D-9881-936087C793A3"
1524528934.722999 [0 127.0.0.1:50690] "SET" "6DAAE2F7-6609-4A5A-88E4-E5F94508F9BA" “{\”different\”:\”response\”}” "PX" "3600000"

Not sure if it helps, but the JSON response for the last SET line where I get no data does not contain the values that I set on response.request.session?.data but it does contain ipaddress and the request's useragent, and a different csrf value.

**Comment by tyressk** [comment]
Ah also I'm getting an `Unexpected json response syntaxError ` on the server log, and the data contains the Redis data in JSON but without a closing bracket `}`.

**Comment by kjessup** [comment]
Just letting you know: I'm still actively trying to reproduce this. If you have any further information that might be helpful, please pass it along.
I will report back once I have something new.

**Comment by kjessup** [comment]
OK I think I found it. `swift package update` and you should get Perfect-Redis version 3.1.1.
Please let me know if this corrects the issue.

**Comment by tyressk** [comment]
Thanks, I've done a couple of hundred requests and cannot reproduce it anymore. Looks fixed now
